### ISSUE TITLE
Compile Warnings

### ISSUE THREAD

**Issue by jsteemann** [neunhoef/CuckooMap#4] opened 2016-12-02 14:47 UTC
When compiling with g++ 5.4 with option -Wextra:
```
/home/steemann/Downloads/CuckooMap/tests/PerformanceTest.cpp: In function ‘int main(int, char**)’:
/home/steemann/Downloads/CuckooMap/tests/PerformanceTest.cpp:211:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             .count() > nMaxTime) {
                      ^
/home/steemann/Downloads/CuckooMap/tests/PerformanceTest.cpp:152:12: warning: unused variable ‘nChunkSize’ [-Wunused-variable]
   uint64_t nChunkSize = 1000000;  // will keep only the most recent X opcounts
            ^
/home/steemann/Downloads/CuckooMap/tests/PerformanceTest.cpp:193:10: warning: unused variable ‘actualInitialSize’ [-Wunused-variable]
   size_t actualInitialSize = MIN(nInitialSize, 1048576);
```
At least the latter looks like it should be
```
   nInitialSize = MIN(nInitialSize, 1048576);
```

**Comment by dhly-etc** [comment] 2016-12-02 15:50
Sorry, yes, this is a bug caused by a previous merge. The `actualInitialSize` variable is used to allocate the table, while `nInitialSize` is used to insert some number of elements. It has been fixed in my current working branches but not propagated to master yet (and I will ensure it propagates when I merge).

**Closed as completed** 2016-12-02 16:16 UTC
